create table hotel (
	hotel_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	hotel_name VARCHAR(17) NOT NULL,
	hotel_phone VARCHAR(50) NOT NULL,
	hotel_email VARCHAR(50) NOT NULL,
	hotel_address VARCHAR(50) NOT NULL,
	hotel_city VARCHAR(8) DEFAULT 'New York',
	website VARCHAR(34) NOT NULL,
	rating VARCHAR(20) NOT NULL,

	FOREIGN KEY (rating) REFERENCES star (rating),
	UNIQUE (hotel_phone),
    UNIQUE (hotel_email),
    UNIQUE (hotel_address),
    UNIQUE (website)
);
insert into hotel (hotel_id, hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values (1, 'Marriott', '617-309-1463', 'solehane0@gov.uk', '054 Bunker Hill Park', 'New York', 'https://www.marriott.com/', 'Three-Star');
insert into hotel (hotel_id, hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values (2, 'Regency', '727-719-3377', 'ecrosi1@weebly.com', '32 Bayside Park', 'New York', 'https://www.regency.com/', 'Four-Star');
insert into hotel (hotel_id, hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values (3, 'Mandarin Oriental', '218-769-9709', 'rhargrove2@ehow.com', '97022 Brickson Park Way', 'New York', 'https://www.mandarin_oriental.com/', 'Five-Star');
insert into hotel (hotel_id, hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values (4, 'El Rancho Casino', '162-836-7828', 'jmattersley3@skyrock.com', '870 Karstens Place', 'New York', 'https://www.el_rancho_casino.com/', 'Four-Star');
insert into hotel (hotel_id, hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values (5, 'Ritz Plaza Hotel', '617-437-9601', 'bphilippault4@wired.com', '058 Truax Crossing', 'New York', 'https://www.ritz_plaza_hotel.com/', 'Five-Star');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Stockholm East (Stockholm Östra)', '337-263-9817', 'jgilardone0@state.tx.us', '9 Lotheville Road', 'New York', 'jmaccaughey0@networksolutions.com', 'Juliana');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Bullet', '771-242-1815', 'ycrichton1@yellowbook.com', '53894 Dovetail Hill', 'New York', 'yspring1@princeton.edu', 'Yorgos');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Starship Troopers', '139-170-5588', 'smckevin2@cargocollective.com', '5 Badeau Park', 'New York', 'sbarrington2@arizona.edu', 'Shawn');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Red Pony, The', '693-116-9380', 'bhritzko3@prlog.org', '2305 Lakeland Circle', 'New York', 'bbaudon3@smugmug.com', 'Bartlett');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Big Trees, The', '422-651-1916', 'kfryman4@dailymail.co.uk', '471 Sundown Way', 'New York', 'kfransseni4@yellowbook.com', 'Kayla');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Shadowlands', '197-826-3220', 'ygleed5@ow.ly', '80642 Northwestern Alley', 'New York', 'ychatainier5@homestead.com', 'Yovonnda');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Terribly Happy (Frygtelig lykkelig)', '761-805-4016', 'tbeavis6@house.gov', '8 Blue Bill Park Alley', 'New York', 'toscroft6@digg.com', 'Tanner');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Musketeer, The', '162-380-3074', 'ecaccavella7@symantec.com', '05524 Dunning Trail', 'New York', 'epohling7@si.edu', 'Eward');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Home and the World, The (Ghare-Baire)', '194-421-1923', 'cginnally8@bloglines.com', '191 Victoria Street', 'New York', 'cstannering8@furl.net', 'Cameron');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('On the Edge', '101-726-7966', 'khutt9@yellowpages.com', '29 Shopko Center', 'New York', 'kgonoude9@csmonitor.com', 'Kylynn');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Ceremony, The (Gishiki)', '419-537-1666', 'cducea@dot.gov', '99565 Thompson Junction', 'New York', 'cdewhursta@netscape.com', 'Claudia');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Accident on Hill Road', '413-999-8946', 'ggreirb@eepurl.com', '18 Merry Circle', 'New York', 'gkyleb@google.pl', 'Geraldine');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Sweet Home', '636-844-2919', 'ccolecroughc@360.cn', '58323 Eagan Parkway', 'New York', 'cnickersonc@redcross.org', 'Camilla');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Day Night Day Night', '245-193-8433', 'phathornd@blogs.com', '5 Mayer Road', 'New York', 'pbatsond@wikimedia.org', 'Puff');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Blindness', '670-304-5686', 'bwoodcocke@prweb.com', '2880 Redwing Crossing', 'New York', 'bvassele@bing.com', 'Borg');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('The Color of Milk', '144-290-5826', 'hkensetf@nhs.uk', '666 Golf View Hill', 'New York', 'hatackf@intel.com', 'Hanan');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Story of the Late Chrysanthemums, The (Zangiku monogatari)', '246-717-0512', 'tbaccasg@skyrock.com', '1898 Shelley Alley', 'New York', 'tlitzmanng@europa.eu', 'Thaddus');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Man''s Best Friend', '612-952-9690', 'mcaunterh@php.net', '18358 Lien Plaza', 'New York', 'mcordobesh@nyu.edu', 'Milty');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('French Connection II', '422-317-9088', 'bjedrykai@delicious.com', '61793 Upham Pass', 'New York', 'blemarchanti@narod.ru', 'Bertine');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Hotte in Paradise (Hotte im Paradies)', '809-928-6914', 'qventonj@cnn.com', '90652 Russell Avenue', 'New York', 'qwatsonbrownj@themeforest.net', 'Quinta');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Wind, The', '611-579-7040', 'ebendellk@techcrunch.com', '4685 Michigan Avenue', 'New York', 'epearminek@ca.gov', 'Erasmus');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Secuestrados (Kidnapped)', '869-848-2308', 'sbogaysl@huffingtonpost.com', '5 Loeprich Trail', 'New York', 'smurrishl@google.de', 'Skippie');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Real Men', '218-527-0541', 'rvearem@biblegateway.com', '8342 Welch Street', 'New York', 'rmoughtinm@bandcamp.com', 'Randall');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Go for Zucker! (Alles auf Zucker!)', '214-453-0786', 'agreenstedn@psu.edu', '83871 Bluestem Junction', 'New York', 'amactaguen@themeforest.net', 'Ashli');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Ugly', '735-560-2199', 'dmulhallo@yahoo.co.jp', '32 Northfield Road', 'New York', 'ddaddao@e-recht24.de', 'Danella');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('2013 Rock and Roll Hall of Fame Induction Ceremony, The', '435-866-9949', 'scallawayp@who.int', '338 Division Drive', 'New York', 'snoenp@ow.ly', 'Sherwynd');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Perfect Crime, The (Crimen Ferpecto) (Ferpect Crime)', '446-480-0172', 'mtrumbleq@google.nl', '061 Raven Hill', 'New York', 'mcorneilq@gnu.org', 'Mitchael');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('OH in Ohio, The', '548-629-1512', 'lfawcusr@biglobe.ne.jp', '6724 Stang Center', 'New York', 'lkemeryr@jigsy.com', 'Lucretia');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Bitter Sweetheart', '168-708-0364', 'mgillmores@jimdo.com', '6 Evergreen Center', 'New York', 'mgianullos@unc.edu', 'Marika');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('The Underneath', '466-946-4828', 'tkleslt@usda.gov', '3819 Old Shore Parkway', 'New York', 'tvandendaelt@businesswire.com', 'Tanitansy');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Sting, The', '203-118-9348', 'vdanbyeu@tmall.com', '2812 John Wall Center', 'New York', 'vrapelliu@sohu.com', 'Van');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Trick or Treat', '188-709-8302', 'tmcareaveyv@drupal.org', '989 Hauk Parkway', 'New York', 'tmicov@cornell.edu', 'Toinette');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Big Girls Don''t Cry... They Get Even (Stepkids)', '667-812-5350', 'klorkinsw@hud.gov', '85 School Crossing', 'New York', 'kbrignallw@nasa.gov', 'Katya');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Jailbait', '398-465-2747', 'gmahareyx@hubpages.com', '83517 Rockefeller Park', 'New York', 'gbrassx@delicious.com', 'Gary');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Champion, The', '439-822-5590', 'nlambshiney@vk.com', '7 Calypso Court', 'New York', 'nbadcocky@list-manage.com', 'Naomi');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Glass Menagerie, The', '334-649-9885', 'dmacgrayz@wikimedia.org', '53 Talisman Place', 'New York', 'dferz@newyorker.com', 'Davina');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Gamera vs. Guiron', '866-220-2821', 'belgar10@theglobeandmail.com', '9775 Clarendon Park', 'New York', 'bflinn10@ox.ac.uk', 'Brendon');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Olsen Gang on the Track, The (Olsen-banden på sporet)', '318-977-4394', 'cgleaves11@sun.com', '04444 Menomonie Place', 'New York', 'cderechter11@google.co.uk', 'Cynthia');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Monsignor', '200-958-9121', 'coldfieldcherry12@imageshack.us', '130 Waywood Plaza', 'New York', 'cmaffetti12@sciencedaily.com', 'Cecil');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Trapped in the Closet: Chapters 1-12', '842-270-6589', 'ngrover13@twitpic.com', '923 Center Park', 'New York', 'ncully13@nymag.com', 'Nye');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Chaos', '934-654-8242', 'lgeaveny14@businessinsider.com', '45 Tennessee Parkway', 'New York', 'lfiske14@ibm.com', 'Lynn');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Amuck!', '613-888-3869', 'jold15@live.com', '1956 Anzinger Junction', 'New York', 'jwitherspoon15@utexas.edu', 'Jackqueline');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('AKA', '759-918-0711', 'dgergler16@china.com.cn', '2 Brown Junction', 'New York', 'dcorson16@cmu.edu', 'Dalis');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Guess Who', '603-627-0579', 'efairhurst17@ox.ac.uk', '797 Doe Crossing Trail', 'New York', 'eberrisford17@amazon.de', 'Edith');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Forever Strong', '112-349-6633', 'jhouselee18@msu.edu', '5 Blackbird Lane', 'New York', 'jbamlet18@shop-pro.jp', 'Jerri');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Why Not Me? (Pourquoi pas moi ?)', '157-865-1613', 'cdeal19@zimbio.com', '3402 Ludington Terrace', 'New York', 'cdickon19@craigslist.org', 'Carlie');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Last Klezmer: Leopold Kozlowski, His Life and Music, The', '697-747-3516', 'cbroxton1a@gizmodo.com', '56363 Goodland Alley', 'New York', 'canselm1a@comcast.net', 'Cornell');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Nazis: A Warning from History, The', '697-530-4036', 'jthresher1b@ebay.co.uk', '83784 Merry Avenue', 'New York', 'jswinden1b@kickstarter.com', 'Janessa');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Too Big to Fail', '989-287-2346', 'mwollers1c@jalbum.net', '9 Drewry Trail', 'New York', 'mmacelholm1c@mozilla.org', 'Malchy');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Fullmetal Alchemist the Movie: Conqueror of Shamballa (Gekijô-ban hagane no renkinjutsushi: Shanbara wo yuku mono)', '122-442-3658', 'coshevlan1d@vimeo.com', '74 Warbler Park', 'New York', 'ctwopenny1d@tumblr.com', 'Claus');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Soft Toilet Seats', '246-656-1313', 'swickes1e@reference.com', '860 Judy Parkway', 'New York', 'sgogarty1e@blog.com', 'Sarah');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Moment by Moment', '188-889-3191', 'ltanti1f@de.vu', '3850 Hallows Point', 'New York', 'lpiggott1f@sakura.ne.jp', 'Lisetta');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Whirlpool', '475-919-8580', 'tshane1g@clickbank.net', '7 Fieldstone Road', 'New York', 'tfolkes1g@merriam-webster.com', 'Tonie');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Junior', '365-159-3443', 'startt1h@people.com.cn', '92 Ramsey Terrace', 'New York', 'sswafford1h@bluehost.com', 'Stefan');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Fantasia', '181-112-9994', 'mswaile1i@privacy.gov.au', '1460 Utah Trail', 'New York', 'mabele1i@china.com.cn', 'Margaux');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Zelig', '645-342-1377', 'emckeney1j@epa.gov', '7278 Dakota Point', 'New York', 'eallsop1j@unesco.org', 'Eddie');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Fat, Sick & Nearly Dead', '358-598-8293', 'csharple1k@dagondesign.com', '132 Merrick Terrace', 'New York', 'clambrook1k@reverbnation.com', 'Claudette');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Spy Kids', '125-225-7222', 'fzealey1l@squarespace.com', '4824 Crescent Oaks Street', 'New York', 'fdesantis1l@illinois.edu', 'Fonz');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Winter of Discontent', '943-820-9739', 'gtrembley1m@theguardian.com', '27926 Gateway Court', 'New York', 'gfloyde1m@admin.ch', 'Garrot');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Internet''s Own Boy: The Story of Aaron Swartz, The', '924-726-0632', 'akenealy1n@netscape.com', '289 Sundown Drive', 'New York', 'aolkowicz1n@slate.com', 'Ashly');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Akeelah and the Bee', '919-760-8587', 'awickerson1o@dailymotion.com', '1 Summerview Terrace', 'New York', 'adelnevo1o@microsoft.com', 'Alyson');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('His Kind of Woman', '755-355-5419', 'jkosel1p@squarespace.com', '9122 Merrick Terrace', 'New York', 'jgillitt1p@scientificamerican.com', 'Joelle');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('More American Graffiti', '688-219-7144', 'cbrunotti1q@msn.com', '7737 Cambridge Circle', 'New York', 'clord1q@youku.com', 'Cristy');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Cinderella Man', '578-379-5636', 'rpell1r@loc.gov', '98 Emmet Hill', 'New York', 'rtettley1r@sbwire.com', 'Randie');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Boricua''s Bond', '382-939-1372', 'apilipyak1s@scientificamerican.com', '82 Algoma Crossing', 'New York', 'acartmer1s@google.pl', 'Aurlie');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Wife, The', '930-656-2705', 'jperfect1t@free.fr', '34704 Texas Road', 'New York', 'jmephan1t@edublogs.org', 'Janice');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Un Piede in paradiso', '623-993-1773', 'dfarens1u@cnbc.com', '25540 Jenna Way', 'New York', 'dblaydes1u@fastcompany.com', 'Debera');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Pathology', '697-330-0121', 'flynnett1v@wiley.com', '92 Monument Trail', 'New York', 'fmacdowal1v@bizjournals.com', 'Frasquito');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Incognito', '919-367-8635', 'ablewett1w@mysql.com', '36 Jay Circle', 'New York', 'abernard1w@topsy.com', 'Aindrea');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Dylan Dog: Dead of Night', '548-533-5946', 'twhitford1x@webs.com', '47 Tony Junction', 'New York', 'tduny1x@purevolume.com', 'Tiffy');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('One Chance', '282-567-1031', 'fbigly1y@geocities.jp', '594 Ridgeway Avenue', 'New York', 'fleicester1y@google.nl', 'Fionna');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('About Last Night...', '799-510-8432', 'tyeomans1z@fastcompany.com', '9812 Monterey Court', 'New York', 'thindrick1z@opensource.org', 'Theresina');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Charlie Chan and the Curse of the Dragon Queen', '801-315-1516', 'mblethin20@indiegogo.com', '2 Alpine Park', 'New York', 'mhand20@tripod.com', 'Mic');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Summertime', '236-195-2890', 'cgiacobbo21@feedburner.com', '4 Riverside Way', 'New York', 'cbrame21@businesswire.com', 'Corrine');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Jonah: A VeggieTales Movie', '330-948-2037', 'hculshew22@unesco.org', '40166 Washington Lane', 'New York', 'hskill22@google.de', 'Harley');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Jungle Man-Eaters', '716-950-8866', 'vmccalum23@gov.uk', '8878 Graedel Pass', 'New York', 'vcornuau23@about.me', 'Vincenty');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Singh Is Kinng', '528-735-6858', 'sbaudinot24@godaddy.com', '38 Gerald Park', 'New York', 'sacres24@yahoo.com', 'Stanton');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Mad Love (Sappho)', '430-570-9939', 'cgarnall25@google.fr', '9 Morningstar Center', 'New York', 'cwraith25@indiegogo.com', 'Caro');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Gett: The Trial of Viviane Amsalem', '664-579-5858', 'dthrush26@prnewswire.com', '84 Shasta Park', 'New York', 'dripping26@narod.ru', 'Dugald');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Brewster''s Millions', '549-134-0040', 'ddeeman27@unblog.fr', '4773 Barby Parkway', 'New York', 'dforryan27@telegraph.co.uk', 'Dixie');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Pandora''s Box (Büchse der Pandora, Die)', '952-220-1058', 'llumbers28@mashable.com', '25782 Fairview Court', 'New York', 'lhambly28@bing.com', 'Laural');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Rapa Nui', '999-828-6773', 'llenox29@illinois.edu', '229 Macpherson Street', 'New York', 'lmacnulty29@ft.com', 'Lanette');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Mrs. Dalloway', '874-306-2739', 'mrushmare2a@archive.org', '38 Anthes Park', 'New York', 'mmcmoyer2a@mapy.cz', 'Modestia');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Slave Ship', '379-113-4373', 'cvallentin2b@pbs.org', '1 Erie Pass', 'New York', 'cprobey2b@blog.com', 'Conney');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Bettie Page Reveals All', '271-202-1995', 'botter2c@so-net.ne.jp', '0 7th Road', 'New York', 'bmcpeice2c@hostgator.com', 'Britt');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('National Treasure: Book of Secrets', '244-722-9298', 'kbram2d@blogtalkradio.com', '107 Sheridan Circle', 'New York', 'kwhoolehan2d@t-online.de', 'Kristen');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Jerky Boys, The', '594-360-4057', 'rlanmeid2e@examiner.com', '40890 Thompson Terrace', 'New York', 'rscates2e@joomla.org', 'Rasla');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Money as Debt', '471-946-9157', 'dbosquet2f@surveymonkey.com', '76 Dorton Crossing', 'New York', 'dharriss2f@yahoo.co.jp', 'Dan');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Beginning of the End', '625-430-3231', 'glilly2g@behance.net', '8 Hintze Hill', 'New York', 'gcovotti2g@ted.com', 'Gordy');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Olive Kitteridge', '828-814-0336', 'gdecruse2h@newyorker.com', '54260 Armistice Circle', 'New York', 'gbalshaw2h@ask.com', 'Gilbertine');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Where the Heart Is', '731-185-1442', 'nkayne2i@answers.com', '93 Blackbird Way', 'New York', 'ncarnock2i@ucsd.edu', 'Nataniel');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Red Road', '562-828-0777', 'jandreas2j@blogspot.com', '439 Pearson Way', 'New York', 'jcaffin2j@comsenz.com', 'Jory');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Abols Upe', '532-858-3238', 'mvigors2k@parallels.com', '31103 Old Gate Center', 'New York', 'msprague2k@hp.com', 'Morrie');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Traffic', '182-266-6946', 'dtire2l@chron.com', '10371 Vera Parkway', 'New York', 'dfarryn2l@census.gov', 'Dani');
insert into hotel (hotel_name, hotel_phone, hotel_email, hotel_address, hotel_city, website, rating) values ('Haiku Tunnel', '773-887-0677', 'lchetham2m@so-net.ne.jp', '5209 Everett Court', 'New York', 'ltomek2m@unesco.org', 'Lester');