create table star (
	rating VARCHAR(20) NOT NULL PRIMARY KEY,
	description TEXT NOT NULL
);

insert into star (rating, description) values ('Three-Star', 'Three-star hotels ordinarily have some unique amenities and provide quality service.');
insert into star (rating, description) values ('Four-Star', 'Four-star hotels are often noted for their upscale quality and extraordinary comfort.');
insert into star (rating, description) values ('Five-Star', 'A five-star property provides flawless guest services in a state-of-the-art facility.');
insert into star (rating, description) values ('Configurable', 'fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis');
insert into star (rating, description) values ('bifurcated', 'at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac');
insert into star (rating, description) values ('system engine', 'gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem');
insert into star (rating, description) values ('project', 'phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus');
insert into star (rating, description) values ('circuit', 'quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet');
insert into star (rating, description) values ('utilisation', 'felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus');
insert into star (rating, description) values ('encompassing', 'nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante');
insert into star (rating, description) values ('archive', 'mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac');
insert into star (rating, description) values ('Extended', 'massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi');
insert into star (rating, description) values ('Pre-emptive', 'amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus');
insert into star (rating, description) values ('exuding', 'vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent');
insert into star (rating, description) values ('6th generation', 'congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam');
insert into star (rating, description) values ('model', 'cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet');
insert into star (rating, description) values ('Open-source', 'vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget');
insert into star (rating, description) values ('heuristic', 'non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet');
insert into star (rating, description) values ('global', 'viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna ac');
insert into star (rating, description) values ('task-force', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur');
insert into star (rating, description) values ('intangible', 'habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi');
insert into star (rating, description) values ('artificial intelligence', 'nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed');
insert into star (rating, description) values ('contingency', 'placerat praesent blandit nam nulla integer pede justo lacinia eget');
insert into star (rating, description) values ('actuating', 'viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec semper sapien a');
insert into star (rating, description) values ('collaboration', 'iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget');
insert into star (rating, description) values ('customer loyalty', 'pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula');
insert into star (rating, description) values ('challenge', 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien');
insert into star (rating, description) values ('info-mediaries', 'non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales');
insert into star (rating, description) values ('client-driven', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus');
insert into star (rating, description) values ('radical', 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem');
insert into star (rating, description) values ('real-time', 'mi pede malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum');
insert into star (rating, description) values ('Upgradable', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla');
insert into star (rating, description) values ('bi-directional', 'mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac');
insert into star (rating, description) values ('Reactive', 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante');
insert into star (rating, description) values ('scalable', 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id');
insert into star (rating, description) values ('Compatible', 'erat volutpat in congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna');
insert into star (rating, description) values ('9star', 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in tempus');
insert into star (rating, description) values ('parallelism', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi');
insert into star (rating, description) values ('Synchronised', 'nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a');
insert into star (rating, description) values ('open system', 'augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis');
insert into star (rating, description) values ('Down-sized', 'lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis a');
insert into star (rating, description) values ('benchmark', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat');
insert into star (rating, description) values ('Realigned', 'tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut');
insert into star (rating, description) values ('Léa', 'duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec');
insert into star (rating, description) values ('Kù', 'sagittis sapien cum sociis natoque penatibus et magnis dis parturient');
insert into star (rating, description) values ('Esbjörn', 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur');
insert into star (rating, description) values ('Yóu', 'ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia');
insert into star (rating, description) values ('Ruì', 'metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna');
insert into star (rating, description) values ('Märta', 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus');
insert into star (rating, description) values ('Amélie', 'quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus');
insert into star (rating, description) values ('Cécilia', 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien');
insert into star (rating, description) values ('Félicie', 'ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum');
insert into star (rating, description) values ('Maïlys', 'et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc');
insert into star (rating, description) values ('Bérengère', 'ut blandit non interdum in ante vestibulum ante ipsum primis in');
insert into star (rating, description) values ('Noëlla', 'amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim');
insert into star (rating, description) values ('Séverine', 'integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam');
insert into star (rating, description) values ('Liè', 'duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis ac');
insert into star (rating, description) values ('Mahélie', 'aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut odio');
insert into star (rating, description) values ('Edmée', 'dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien');
insert into star (rating, description) values ('Mégane', 'velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum');
insert into star (rating, description) values ('Lauréna', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris');
insert into star (rating, description) values ('Océane', 'faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at');
insert into star (rating, description) values ('Léandre', 'pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu');
insert into star (rating, description) values ('Nadège', 'faucibus orci luctus et ultrices posuere cubilia curae donec pharetra');
insert into star (rating, description) values ('Inès', 'lectus pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis');
insert into star (rating, description) values ('Maëlann', 'in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed');
insert into star (rating, description) values ('Dù', 'nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper');
insert into star (rating, description) values ('Björn', 'pede lobortis ligula sit amet eleifend pede libero quis orci nullam molestie nibh in');
insert into star (rating, description) values ('Magdalène', 'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor');
insert into star (rating, description) values ('Mårten', 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est');
insert into star (rating, description) values ('Joséphine', 'et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis');
insert into star (rating, description) values ('Erwéi', 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus');
insert into star (rating, description) values ('Nélie', 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit');
insert into star (rating, description) values ('Hélèna', 'et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor');
insert into star (rating, description) values ('Speotyte cuniculata', 'primis in faucibus orci luctus et ultrices posuere cubilia curae mauris');
insert into star (rating, description) values ('Naja haje', 'hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget orci');
insert into star (rating, description) values ('Vanellus sp.', 'tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit');
insert into star (rating, description) values ('Climacteris melanura', 'nibh in lectus pellentesque at nulla suspendisse potenti cras in purus eu');
insert into star (rating, description) values ('Ictonyx striatus', 'bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at');
insert into star (rating, description) values ('Sagittarius serpentarius', 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim');
insert into star (rating, description) values ('Felis chaus', 'vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla');
insert into star (rating, description) values ('Antechinus flavipes', 'consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien');
insert into star (rating, description) values ('Connochaetus taurinus', 'suspendisse potenti cras in purus eu magna vulputate luctus cum sociis natoque');
insert into star (rating, description) values ('Pytilia melba', 'porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non');
insert into star (rating, description) values ('Alligator mississippiensis', 'ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac');
insert into star (rating, description) values ('Ovis orientalis', 'sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede');
insert into star (rating, description) values ('Columba livia', 'ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut');
insert into star (rating, description) values ('Bison bison', 'nulla suspendisse potenti cras in purus eu magna vulputate luctus cum');
insert into star (rating, description) values ('Loris tardigratus', 'vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae');
insert into star (rating, description) values ('Choloepus hoffmani', 'vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci eget');
insert into star (rating, description) values ('Nasua nasua', 'urna pretium nisl ut volutpat sapien arcu sed augue aliquam');
insert into star (rating, description) values ('Aonyx cinerea', 'tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi');
insert into star (rating, description) values ('Plocepasser mahali', 'cras in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient montes');
insert into star (rating, description) values ('Ardea golieth', 'molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas');
insert into star (rating, description) values ('unavailable', 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit');
insert into star (rating, description) values ('Tragelaphus angasi', 'sed tristique in tempus sit amet sem fusce consequat nulla nisl');
insert into star (rating, description) values ('Sarcophilus harrisii', 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi');
insert into star (rating, description) values ('Deroptyus accipitrinus', 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis');
insert into star (rating, description) values ('Melursus ursinus', 'in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui');
insert into star (rating, description) values ('Canis latrans', 'sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at');
insert into star (rating, description) values ('Ninox superciliaris', 'lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu');
insert into star (rating, description) values ('Lepilemur rufescens', 'ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra');
insert into star (rating, description) values ('Papio cynocephalus', 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam');
insert into star (rating, description) values ('Chelodina longicollis', 'tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id');
insert into star (rating, description) values ('Coluber constrictor', 'primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis');
insert into star (rating, description) values ('Gopherus agassizii', 'sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit');
insert into star (rating, description) values ('Scolopax minor', 'mauris morbi non lectus aliquam sit amet diam in magna');